### ISSUE TITLE
Script fails if any single key is not found

### ISSUE THREAD

**Issue by gumispl** [pawel-slowik/play-scraper#2]
It seems that different tariffs use different labels and script fails if any single key is not found.
For example in my tariff "Play na Kartę odNOWA" there is no key "Liczba promocyjnych GB" and it is causing rest of the script to fail.
The script should just skip any lines that were not found.

**Comment by pawel-slowik** [comment]
I have changed the way HTML parsing works. Among other things, it shouldn't crash on missing labels. Can you please update and test it?

**Comment by gumispl** [comment]
Yes it now skips missing labels correctly.
Also after modifying BALANCE_PARSERS iterable I was able to get desirable entries :)
